onEvent('recipes', e => {
  e.remove({ id: 'akashictome:tome' })

  e.shapeless(
    Item.of('akashictome:tome', {
      "akashictome:is_morphing":1,
      "akashictome:data":{
        "industrialforegoing":{
          "id":"patchouli:guide_book",
          "Count":1,
          "tag":{
            "akashictome:displayName":{
              "text":"IndustrialForegoing'sManual"
            },
            "patchouli:book":"industrialforegoing:industrial_foregoing"
          }
        },
        "resourcefulbees":{
          "id":"patchouli:guide_book",
          "Count":1,
          "tag":{
            "akashictome:displayName":{
              "text":"FiftyShadesofBees"
            },
            "patchouli:book":"resourcefulbees:fifty_shades_of_bees",
            "akashictome:is_morphing":1,
            "display":{
              "Name":"{\"translate\":\"akashictome.sudo_name\",\"with\":[{\"color\":\"green\",\"text\":\"FiftyShadesofBees\"}]}"
            }
          }
        },
        "astralsorcery":{
          "id":"astralsorcery:tome",
          "Count":1,
          "tag":{
            "akashictome:displayName":{
              "text":"AstralTome"
            }
          }
        },
        "theoneprobe":{
          "id":"theoneprobe:probenote",
          "Count":1,
          "tag":{
            "akashictome:displayName":{
              "text":"ProbeSettings"
            },
            "akashictome:is_morphing":1
          }
        },
        "psi":{
          "id":"patchouli:guide_book",
          "Count":1,
          "tag":{
            "akashictome:displayName":{
              "text":"EncylopaediaPsionica"
            },
            "patchouli:book":"psi:encyclopaedia_psionica"
          }
        },
        "immersiveengineering":{
          "id":"immersiveengineering:manual",
          "Count":1,
          "tag":{
            "akashictome:displayName":{
              "text":"Engineer'sManual"
            },
            "akashictome:is_morphing":1,
            "display":{
              "Name":"{\"translate\":\"akashictome.sudo_name\",\"with\":[{\"color\":\"green\",\"text\":\"Engineer\\\\'sManual\"}]}"
            }
          }
        },
        "advancedperipherals":{
          "id":"patchouli:guide_book",
          "Count":1,
          "tag":{
            "akashictome:displayName":{
              "text":"Advanced Peripherals"
            },
            "patchouli:book":"advancedperipherals:manual"
          }
        },
        "eidolon":{
          "id":"eidolon:codex",
          "Count":1,
          "tag":{
            "akashictome:displayName":{
              "text":"ArsEcclesia"
            },
            "akashictome:is_morphing":1,
            "display":{
              "Name":"{\"translate\":\"akashictome.sudo_name\",\"with\":[{\"color\":\"green\",\"text\":\"ArsEcclesia\"}]}"
            }
          }
        },
        "elementalcraft":{
          "id":"patchouli:guide_book",
          "Count":1,
          "tag":{
            "akashictome:displayName":{
              "text":"Elementopedia"
            },
            "patchouli:book":"elementalcraft:element_book",
            "akashictome:is_morphing":1,
            "display":{
              "Name":"{\"translate\":\"akashictome.sudo_name\",\"with\":[{\"color\":\"green\",\"text\":\"Elementopedia\"}]}"
            }
          }
        },
        "silentgear":{
          "id":"silentgear:guide_book",
          "Count":1,
          "tag":{
            "akashictome:displayName":{
              "text":"SilentGearGuide"
            }
          }
        },
        "botania":{
          "id":"botania:lexicon",
          "Count":1,
          "tag":{
            "akashictome:displayName":{
              "text":"LexicaBotania"
            },
            "botania:elven_unlock":1,
            "display":{
              "Name":"{\"translate\":\"akashictome.sudo_name\",\"with\":[{\"color\":\"green\",\"text\":\"LexicaBotania\"}]}"
            },
            "akashictome:is_morphing":1
          }
        },
        "feywild":{
          "id":"feywild:feywild_lexicon",
          "Count":1,
          "tag":{
            "akashictome:displayName":{
              "text":"Feywild Lexicon"
            },
            "akashictome:is_morphing":1,
            "display":{
              "Name":"{\"translate\":\"akashictome.sudo_name\",\"with\":[{\"color\":\"green\",\"text\":\"Feywild Lexicon\"}]}"
            }
          }
        },
        "thermal":{
          "id":"patchouli:guide_book",
          "Count":1,
          "tag":{
            "akashictome:displayName":{
              "text":"Thermalpedia"
            },
            "patchouli:book":"thermal:guidebook"
          }
        },
        "rftoolsbase":{
          "id":"rftoolsbase:manual",
          "Count":1,
          "tag":{
            "akashictome:displayName":{
              "text":"TechnologyGuide"
            },
            "akashictome:is_morphing":1,
            "display":{
              "Name":"{\"translate\":\"akashictome.sudo_name\",\"with\":[{\"color\":\"green\",\"text\":\"TechnologyGuide\"}]}"
            }
          }
        },
        "witchery_rewitched":{
          "id":"patchouli:guide_book",
          "Count":1,
          "tag":{
            "akashictome:displayName":{
              "text":"The Lexicon of Witching"
            },
            "patchouli:book":"witchery_rewitched:circles_and_rites",
            "akashictome:is_morphing":1,
            "display":{
              "Name":"{\"translate\":\"akashictome.sudo_name\",\"with\":[{\"color\":\"green\",\"text\":\"The Lexicon of Witching\"}]}"
            }
          }
        },
        "storagenetwork":{
          "id":"patchouli:guide_book",
          "Count":1,
          "tag":{
            "akashictome:displayName":{
              "text":"Network Guide Book"
            },
            "patchouli:book":"storagenetwork:network_book",
            "akashictome:is_morphing":1,
            "display":{
              "Name":"{\"translate\":\"akashictome.sudo_name\",\"with\":[{\"color\":\"green\",\"text\":\"Network Guide Book\"}]}"
            }
          }
        },
        "integratedtunnels":{
          "id":"integrateddynamics:on_the_dynamics_of_integration",
          "Count":1,
          "tag":{
            "akashictome:displayName":{
              "text":"OnTheDynamicsOfIntegration"
            }
          }
        },
        "powah":{
          "id":"powah:book",
          "Count":1,
          "tag":{
            "akashictome:displayName":{
              "text":"Manual(Powah!)"
            },
            "akashictome:is_morphing":1,
            "display":{
              "Name":"{\"translate\":\"akashictome.sudo_name\",\"with\":[{\"color\":\"green\",\"text\":\"Manual(Powah!)\"}]}"
            }
          }
        },
        "pneumaticcraft":{
          "id":"patchouli:guide_book",
          "Count":1,
          "tag":{
            "akashictome:displayName":{
              "text":"PNC:RManual"
            },
            "patchouli:book":"pneumaticcraft:book"
          }
        },
        "naturesaura":{
          "id":"patchouli:guide_book",
          "Count":1,
          "tag":{
            "akashictome:displayName":{
              "text":"BookOfNaturalAura"
            },
            "patchouli:book":"naturesaura:book"
          }
        },
        "engineersdecor":{
          "id":"patchouli:guide_book",
          "Count":1,
          "tag":{
            "akashictome:displayName":{
              "text":"Engineer'sDecor"
            },
            "patchouli:book":"engineersdecor:engineersdecor_manual"
          }
        },
        "mahoutsukai":{
          "id":"mahoutsukai:guidebook",
          "Count":1,
          "tag":{
            "akashictome:displayName":{
              "text":"MahouTsukaiKnowledgeCompendium"
            },
            "akashictome:is_morphing":1,
            "display":{
              "Name":"{\"translate\":\"akashictome.sudo_name\",\"with\":[{\"color\":\"green\",\"text\":\"MahouTsukaiKnowledgeCompendium\"}]}"
            }
          }
        },
        "occultism":{
          "id":"occultism:dictionary_of_spirits",
          "Count":1,
          "tag":{
            "akashictome:displayName":{
              "text":"Dictionary of Spirits"
            },
            "akashictome:is_morphing":1,
            "display":{
              "Name":"{\"translate\":\"akashictome.sudo_name\",\"with\":[{\"color\":\"green\",\"text\":\"Dictionary of Spirits\"}]}"
            }
          }
        },
        "solcarrot":{
          "id":"solcarrot:food_book",
          "Count":1,
          "tag":{
            "akashictome:displayName":{
              "text":"FoodBook"
            },
            "akashictome:is_morphing":1,
            "display":{
              "Name":"{\"translate\":\"akashictome.sudo_name\",\"with\":[{\"color\":\"green\",\"text\":\"FoodBook\"}]}"
            }
          }
        },
        "modularrouters":{
          "id":"patchouli:guide_book",
          "Count":1,
          "tag":{
            "akashictome:displayName":{
              "text":"ModularRoutersManual"
            },
            "patchouli:book":"modularrouters:book"
          }
        },
        "ars_nouveau":{
          "id":"ars_nouveau:worn_notebook",
          "Count":1,
          "tag":{
            "akashictome:displayName":{
              "text":"WornNotebook"
            }
          }
        },
        "bloodmagic":{
          "id":"patchouli:guide_book",
          "Count":1,
          "tag":{
            "akashictome:displayName":{
              "text":"SanguineScientiem"
            },
            "patchouli:book":"bloodmagic:guide",
            "akashictome:is_morphing":1,
            "display":{
              "Name":"{\"translate\":\"akashictome.sudo_name\",\"with\":[{\"color\":\"green\",\"text\":\"SanguineScientiem\"}]}"
            }
          }
        },
        "mysticalagriculture":{
          "id":"patchouli:guide_book",
          "Count":1,
          "tag":{
            "akashictome:displayName":{
              "text":"MysticalAgriculture"
            },
            "patchouli:book":"mysticalagriculture:guide",
            "akashictome:is_morphing":1,
            "display":{
              "Name":"{\"translate\":\"akashictome.sudo_name\",\"with\":[{\"color\":\"green\",\"text\":\"MysticalAgriculture\"}]}"
            }
          }
        }
      }
    }),
    'minecraft:stick'
  ).id(`kubejs:akashik_tome`)
})
